# Generated by Django 3.2.11 on 2022-02-25 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seriados', '0002_auto_20220202_0046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodio',
            options={'verbose_name': 'Episódio', 'verbose_name_plural': 'Episódios'},
        ),
        migrations.AlterModelOptions(
            name='reviewepisodio',
            options={'verbose_name': 'Review do Episódio', 'verbose_name_plural': 'Reviews dos Episódios'},
        ),
        migrations.AlterModelOptions(
            name='revisor',
            options={'verbose_name': 'Revisor', 'verbose_name_plural': 'Revisores'},
        ),
        migrations.AlterModelOptions(
            name='serie',
            options={'verbose_name': 'Série', 'verbose_name_plural': 'Séries'},
        ),
        migrations.AlterModelOptions(
            name='temporada',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterField(
            model_name='episodio',
            name='data',
            field=models.DateField(verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.temporada', verbose_name='Temporada'),
        ),
        migrations.AlterField(
            model_name='episodio',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='episodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.episodio', verbose_name='Episódio'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='nota',
            field=models.CharField(choices=[('A', 'Excelente'), ('B', 'Bom'), ('C', 'Ruim')], default='B', max_length=1, verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='reviewepisodio',
            name='revisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.revisor', verbose_name='Revisor'),
        ),
        migrations.AlterField(
            model_name='revisor',
            name='reviews_episodios',
            field=models.ManyToManyField(related_name='review', through='seriados.ReviewEpisodio', to='seriados.Episodio', verbose_name='Review do Episódio'),
        ),
        migrations.AlterField(
            model_name='revisor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='nome',
            field=models.CharField(max_length=70, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='numero',
            field=models.IntegerField(verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seriados.serie', verbose_name='Série'),
        ),
    ]
